apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: file.csi.azure.com
  name: pv-azurefile
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain  # if set as "Delete" file share would be removed in pvc deletion
  storageClassName: azurefile-csi
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=0
    - gid=0
    - mfsymlinks
    - cache=strict  
    - nosharesock
  csi:
    driver: file.csi.azure.com
    # make sure volumeid is unique for every identical share in the cluster
    volumeHandle: sasubfinledgerqa01_hlf
    volumeAttributes:
      shareName: hlf  # only file share name, don't use full path
    nodeStageSecretRef:
      name: sc-qa-accesskey
      namespace: finledger